/* AUTO-GENERATED from tokens.css — do not edit by hand.
   Edit tokens.css and run: nx run ui-kit:generate-tokens */

export const PRIMITIVE_TOKENS = [
  'c-n-0',
  'c-n-50',
  'c-n-100',
  'c-n-150',
  'c-n-200',
  'c-n-300',
  'c-n-400',
  'c-n-500',
  'c-n-600',
  'c-n-700',
  'c-n-800',
  'c-n-900',
  'c-n-1000',
  'c-accent-100',
  'c-accent-200',
  'c-accent-300',
  'c-accent-400',
  'c-accent-500',
  'c-accent',
  'c-accent-600',
  'c-accent-700',
  'c-accent-800',
  'c-accent-900',
  'c-danger-100',
  'c-danger-300',
  'c-danger-500',
  'c-danger-700',
  'c-success-100',
  'c-success-300',
  'c-success-500',
  'c-success-700',
  'c-info-100',
  'c-info-300',
  'c-info-500',
  'c-info-700',
] as const;
export type PrimitiveToken = (typeof PRIMITIVE_TOKENS)[number];

export const TOKENS = [
  'font-ui',
  'font-mono',
  'bg-canvas',
  'bg-surface',
  'bg-raised',
  'bg-sunken',
  'bg-hover',
  'bg-active',
  'bg-selected',
  'bg-accent-soft',
  'bg-danger-soft',
  'bg-danger-hover',
  'bg-danger-active',
  'bg-scrim',
  'bg-scrim-light',
  'text-primary',
  'text-secondary',
  'text-muted',
  'text-disabled',
  'text-inverse',
  'text-accent',
  'text-on-accent',
  'text-danger',
  'border-hairline',
  'border-strong',
  'border-accent',
  'border-danger',
  'focus-ring',
  'state-overdue',
  'state-due-soon',
  'state-done',
  'state-info',
  'state-pending',
  'state-conflict',
  'shadow-raised',
  'shadow-overlay',
  'shadow-modal',
  'kbd-bg',
  'kbd-border',
  'kbd-fg',
  'bg-track',
  'bg-accent-hover',
  'bg-accent-active',
  'border-accent-strong',
  'bg-selection',
  'text-placeholder',
  'switch-thumb-off',
  'tag-neutral-bg',
  'avatar-bg-1',
  'avatar-bg-2',
  'avatar-bg-3',
  'avatar-bg-4',
  'avatar-fg',
  'avatar-empty',
  'tint-dot-l',
  'tint-dot-c',
  'tint-fill-l',
  'tint-fill-c',
  'tint-fill-alpha',
  'tint-text-l',
  'tint-text-c',
  'num-tabular',
  'type-display',
  'lh-display',
  'type-h1',
  'lh-h1',
  'type-h2',
  'lh-h2',
  'type-h3',
  'lh-h3',
  'type-body',
  'lh-body',
  'type-meta',
  'lh-meta',
  'weight-normal',
  'weight-strong',
  'line-clamp-title',
  'sp-1',
  'sp-2',
  'sp-3',
  'sp-4',
  'sp-5',
  'sp-6',
  'sp-7',
  'sp-8',
  'radius-xs',
  'radius-sm',
  'radius-md',
  'radius-full',
  'border-width',
  'border-width-strong',
  'focus-offset',
  'overlay-margin',
  'menu-offset',
  'overlay-enter-scale',
  'dur-state',
  'dur-exit',
  'dur-layer',
  'dur-panel',
  'dur-move',
  'ease-out',
  'ease-in',
  'ease-inout',
  'z-content',
  'z-sticky',
  'z-shell',
  'z-drag',
  'z-dropdown',
  'z-layer',
  'z-toast',
  'z-tooltip',
  'sidebar-width',
  'sidebar-min',
  'sidebar-max',
  'sidebar-snap',
  'sidebar-collapsed',
  'panel-width',
  'panel-min',
  'panel-max',
  'canvas-min',
  'panel-enter',
  'panel-enter-shift',
  'resizer-hit',
  'resizer-delay',
  'resize-step',
  'resize-step-big',
  'canvas-header-height',
  'statusbar-height',
  'column-width',
  'column-gap',
  'icon-size',
  'icon-stroke',
  'icon-size-lg',
  'avatar-xs',
  'avatar-sm',
  'avatar-md',
  'avatar-stack-max',
  'avatar-overlap',
  'palette-width',
  'palette-row',
  'palette-input',
  'palette-max',
  'dialog-top',
  'palette-enter',
  'palette-exit',
  'kbd-size',
  'kbd-font-size',
  'visually-hidden-size',
  'spin-duration',
  'spinner-size-xs',
  'spinner-size-sm',
  'spinner-size-md',
  'spinner-size-lg',
  'spinner-stroke-thin',
  'spinner-stroke-thick',
  'spinner-delay',
  'spinner-min',
  'progress-height',
  'progress-run',
  'progress-breath',
  'progress-transition',
  'tooltip-max-width',
  'tooltip-offset',
  'tooltip-pad-y',
  'tooltip-pad-x',
  'tooltip-group-window',
  'disabled-opacity',
  'button-gap',
  'button-gap-sm',
  'input-state',
  'input-gap',
  'textarea-max-rows',
  'pending-dot-size',
  'highlight-remote-easing',
  'checkbox-size',
  'checkbox-glyph-size',
  'checkbox-state',
  'switch-width',
  'switch-height',
  'switch-thumb',
  'switch-thumb-stretch',
  'switch-inset',
  'switch-state',
  'menu-min-width',
  'menu-max-width',
  'menu-max-items',
  'menu-radio-dot',
  'menu-enter',
  'menu-exit',
  'popover-width',
  'popover-width-wide',
  'popover-enter',
  'popover-exit',
  'tag-height',
  'tag-dot',
  'tag-icon-size',
  'tag-max-visible',
  'tag-state',
  'segmented-pad-x',
  'segmented-pad-x-sm',
  'segmented-state',
  'undo-window',
  'tooltip-delay',
  'highlight-remote',
  'drag-threshold',
  'row-height',
  'control-height',
  'control-height-sm',
  'card-padding',
  'card-gap',
  'cell-padding-x',
  'hit-min',
  'button-pad-x',
  'button-pad-x-sm',
  'input-pad-x',
  'segmented-height',
] as const;
/** Token names of layers 2-3. Primitives (--c-*) are excluded on purpose: a component never sees them. */
export type TokenName = (typeof TOKENS)[number];

/** name → 'var(--name)'. For inline styles and CSS-in-JS. */
export const token = {
  'font-ui': 'var(--font-ui)',
  'font-mono': 'var(--font-mono)',
  'bg-canvas': 'var(--bg-canvas)',
  'bg-surface': 'var(--bg-surface)',
  'bg-raised': 'var(--bg-raised)',
  'bg-sunken': 'var(--bg-sunken)',
  'bg-hover': 'var(--bg-hover)',
  'bg-active': 'var(--bg-active)',
  'bg-selected': 'var(--bg-selected)',
  'bg-accent-soft': 'var(--bg-accent-soft)',
  'bg-danger-soft': 'var(--bg-danger-soft)',
  'bg-danger-hover': 'var(--bg-danger-hover)',
  'bg-danger-active': 'var(--bg-danger-active)',
  'bg-scrim': 'var(--bg-scrim)',
  'bg-scrim-light': 'var(--bg-scrim-light)',
  'text-primary': 'var(--text-primary)',
  'text-secondary': 'var(--text-secondary)',
  'text-muted': 'var(--text-muted)',
  'text-disabled': 'var(--text-disabled)',
  'text-inverse': 'var(--text-inverse)',
  'text-accent': 'var(--text-accent)',
  'text-on-accent': 'var(--text-on-accent)',
  'text-danger': 'var(--text-danger)',
  'border-hairline': 'var(--border-hairline)',
  'border-strong': 'var(--border-strong)',
  'border-accent': 'var(--border-accent)',
  'border-danger': 'var(--border-danger)',
  'focus-ring': 'var(--focus-ring)',
  'state-overdue': 'var(--state-overdue)',
  'state-due-soon': 'var(--state-due-soon)',
  'state-done': 'var(--state-done)',
  'state-info': 'var(--state-info)',
  'state-pending': 'var(--state-pending)',
  'state-conflict': 'var(--state-conflict)',
  'shadow-raised': 'var(--shadow-raised)',
  'shadow-overlay': 'var(--shadow-overlay)',
  'shadow-modal': 'var(--shadow-modal)',
  'kbd-bg': 'var(--kbd-bg)',
  'kbd-border': 'var(--kbd-border)',
  'kbd-fg': 'var(--kbd-fg)',
  'bg-track': 'var(--bg-track)',
  'bg-accent-hover': 'var(--bg-accent-hover)',
  'bg-accent-active': 'var(--bg-accent-active)',
  'border-accent-strong': 'var(--border-accent-strong)',
  'bg-selection': 'var(--bg-selection)',
  'text-placeholder': 'var(--text-placeholder)',
  'switch-thumb-off': 'var(--switch-thumb-off)',
  'tag-neutral-bg': 'var(--tag-neutral-bg)',
  'avatar-bg-1': 'var(--avatar-bg-1)',
  'avatar-bg-2': 'var(--avatar-bg-2)',
  'avatar-bg-3': 'var(--avatar-bg-3)',
  'avatar-bg-4': 'var(--avatar-bg-4)',
  'avatar-fg': 'var(--avatar-fg)',
  'avatar-empty': 'var(--avatar-empty)',
  'tint-dot-l': 'var(--tint-dot-l)',
  'tint-dot-c': 'var(--tint-dot-c)',
  'tint-fill-l': 'var(--tint-fill-l)',
  'tint-fill-c': 'var(--tint-fill-c)',
  'tint-fill-alpha': 'var(--tint-fill-alpha)',
  'tint-text-l': 'var(--tint-text-l)',
  'tint-text-c': 'var(--tint-text-c)',
  'num-tabular': 'var(--num-tabular)',
  'type-display': 'var(--type-display)',
  'lh-display': 'var(--lh-display)',
  'type-h1': 'var(--type-h1)',
  'lh-h1': 'var(--lh-h1)',
  'type-h2': 'var(--type-h2)',
  'lh-h2': 'var(--lh-h2)',
  'type-h3': 'var(--type-h3)',
  'lh-h3': 'var(--lh-h3)',
  'type-body': 'var(--type-body)',
  'lh-body': 'var(--lh-body)',
  'type-meta': 'var(--type-meta)',
  'lh-meta': 'var(--lh-meta)',
  'weight-normal': 'var(--weight-normal)',
  'weight-strong': 'var(--weight-strong)',
  'line-clamp-title': 'var(--line-clamp-title)',
  'sp-1': 'var(--sp-1)',
  'sp-2': 'var(--sp-2)',
  'sp-3': 'var(--sp-3)',
  'sp-4': 'var(--sp-4)',
  'sp-5': 'var(--sp-5)',
  'sp-6': 'var(--sp-6)',
  'sp-7': 'var(--sp-7)',
  'sp-8': 'var(--sp-8)',
  'radius-xs': 'var(--radius-xs)',
  'radius-sm': 'var(--radius-sm)',
  'radius-md': 'var(--radius-md)',
  'radius-full': 'var(--radius-full)',
  'border-width': 'var(--border-width)',
  'border-width-strong': 'var(--border-width-strong)',
  'focus-offset': 'var(--focus-offset)',
  'overlay-margin': 'var(--overlay-margin)',
  'menu-offset': 'var(--menu-offset)',
  'overlay-enter-scale': 'var(--overlay-enter-scale)',
  'dur-state': 'var(--dur-state)',
  'dur-exit': 'var(--dur-exit)',
  'dur-layer': 'var(--dur-layer)',
  'dur-panel': 'var(--dur-panel)',
  'dur-move': 'var(--dur-move)',
  'ease-out': 'var(--ease-out)',
  'ease-in': 'var(--ease-in)',
  'ease-inout': 'var(--ease-inout)',
  'z-content': 'var(--z-content)',
  'z-sticky': 'var(--z-sticky)',
  'z-shell': 'var(--z-shell)',
  'z-drag': 'var(--z-drag)',
  'z-dropdown': 'var(--z-dropdown)',
  'z-layer': 'var(--z-layer)',
  'z-toast': 'var(--z-toast)',
  'z-tooltip': 'var(--z-tooltip)',
  'sidebar-width': 'var(--sidebar-width)',
  'sidebar-min': 'var(--sidebar-min)',
  'sidebar-max': 'var(--sidebar-max)',
  'sidebar-snap': 'var(--sidebar-snap)',
  'sidebar-collapsed': 'var(--sidebar-collapsed)',
  'panel-width': 'var(--panel-width)',
  'panel-min': 'var(--panel-min)',
  'panel-max': 'var(--panel-max)',
  'canvas-min': 'var(--canvas-min)',
  'panel-enter': 'var(--panel-enter)',
  'panel-enter-shift': 'var(--panel-enter-shift)',
  'resizer-hit': 'var(--resizer-hit)',
  'resizer-delay': 'var(--resizer-delay)',
  'resize-step': 'var(--resize-step)',
  'resize-step-big': 'var(--resize-step-big)',
  'canvas-header-height': 'var(--canvas-header-height)',
  'statusbar-height': 'var(--statusbar-height)',
  'column-width': 'var(--column-width)',
  'column-gap': 'var(--column-gap)',
  'icon-size': 'var(--icon-size)',
  'icon-stroke': 'var(--icon-stroke)',
  'icon-size-lg': 'var(--icon-size-lg)',
  'avatar-xs': 'var(--avatar-xs)',
  'avatar-sm': 'var(--avatar-sm)',
  'avatar-md': 'var(--avatar-md)',
  'avatar-stack-max': 'var(--avatar-stack-max)',
  'avatar-overlap': 'var(--avatar-overlap)',
  'palette-width': 'var(--palette-width)',
  'palette-row': 'var(--palette-row)',
  'palette-input': 'var(--palette-input)',
  'palette-max': 'var(--palette-max)',
  'dialog-top': 'var(--dialog-top)',
  'palette-enter': 'var(--palette-enter)',
  'palette-exit': 'var(--palette-exit)',
  'kbd-size': 'var(--kbd-size)',
  'kbd-font-size': 'var(--kbd-font-size)',
  'visually-hidden-size': 'var(--visually-hidden-size)',
  'spin-duration': 'var(--spin-duration)',
  'spinner-size-xs': 'var(--spinner-size-xs)',
  'spinner-size-sm': 'var(--spinner-size-sm)',
  'spinner-size-md': 'var(--spinner-size-md)',
  'spinner-size-lg': 'var(--spinner-size-lg)',
  'spinner-stroke-thin': 'var(--spinner-stroke-thin)',
  'spinner-stroke-thick': 'var(--spinner-stroke-thick)',
  'spinner-delay': 'var(--spinner-delay)',
  'spinner-min': 'var(--spinner-min)',
  'progress-height': 'var(--progress-height)',
  'progress-run': 'var(--progress-run)',
  'progress-breath': 'var(--progress-breath)',
  'progress-transition': 'var(--progress-transition)',
  'tooltip-max-width': 'var(--tooltip-max-width)',
  'tooltip-offset': 'var(--tooltip-offset)',
  'tooltip-pad-y': 'var(--tooltip-pad-y)',
  'tooltip-pad-x': 'var(--tooltip-pad-x)',
  'tooltip-group-window': 'var(--tooltip-group-window)',
  'disabled-opacity': 'var(--disabled-opacity)',
  'button-gap': 'var(--button-gap)',
  'button-gap-sm': 'var(--button-gap-sm)',
  'input-state': 'var(--input-state)',
  'input-gap': 'var(--input-gap)',
  'textarea-max-rows': 'var(--textarea-max-rows)',
  'pending-dot-size': 'var(--pending-dot-size)',
  'highlight-remote-easing': 'var(--highlight-remote-easing)',
  'checkbox-size': 'var(--checkbox-size)',
  'checkbox-glyph-size': 'var(--checkbox-glyph-size)',
  'checkbox-state': 'var(--checkbox-state)',
  'switch-width': 'var(--switch-width)',
  'switch-height': 'var(--switch-height)',
  'switch-thumb': 'var(--switch-thumb)',
  'switch-thumb-stretch': 'var(--switch-thumb-stretch)',
  'switch-inset': 'var(--switch-inset)',
  'switch-state': 'var(--switch-state)',
  'menu-min-width': 'var(--menu-min-width)',
  'menu-max-width': 'var(--menu-max-width)',
  'menu-max-items': 'var(--menu-max-items)',
  'menu-radio-dot': 'var(--menu-radio-dot)',
  'menu-enter': 'var(--menu-enter)',
  'menu-exit': 'var(--menu-exit)',
  'popover-width': 'var(--popover-width)',
  'popover-width-wide': 'var(--popover-width-wide)',
  'popover-enter': 'var(--popover-enter)',
  'popover-exit': 'var(--popover-exit)',
  'tag-height': 'var(--tag-height)',
  'tag-dot': 'var(--tag-dot)',
  'tag-icon-size': 'var(--tag-icon-size)',
  'tag-max-visible': 'var(--tag-max-visible)',
  'tag-state': 'var(--tag-state)',
  'segmented-pad-x': 'var(--segmented-pad-x)',
  'segmented-pad-x-sm': 'var(--segmented-pad-x-sm)',
  'segmented-state': 'var(--segmented-state)',
  'undo-window': 'var(--undo-window)',
  'tooltip-delay': 'var(--tooltip-delay)',
  'highlight-remote': 'var(--highlight-remote)',
  'drag-threshold': 'var(--drag-threshold)',
  'row-height': 'var(--row-height)',
  'control-height': 'var(--control-height)',
  'control-height-sm': 'var(--control-height-sm)',
  'card-padding': 'var(--card-padding)',
  'card-gap': 'var(--card-gap)',
  'cell-padding-x': 'var(--cell-padding-x)',
  'hit-min': 'var(--hit-min)',
  'button-pad-x': 'var(--button-pad-x)',
  'button-pad-x-sm': 'var(--button-pad-x-sm)',
  'input-pad-x': 'var(--input-pad-x)',
  'segmented-height': 'var(--segmented-height)',
} as const satisfies Record<TokenName, string>;

/** Scalar values (px/ms/unitless) from the base :root — for JS logic. */
export const raw = {
  'tint-dot-l': 0.555,
  'tint-dot-c': 0.15,
  'tint-fill-l': 0.954,
  'tint-fill-c': 0.02,
  'tint-fill-alpha': 1,
  'tint-text-l': 0.43,
  'tint-text-c': 0.13,
  'type-display': 28,
  'lh-display': 1.2,
  'type-h1': 22,
  'lh-h1': 1.25,
  'type-h2': 18,
  'lh-h2': 1.3,
  'type-h3': 15,
  'lh-h3': 1.4,
  'type-body': 14,
  'lh-body': 1.5,
  'type-meta': 12,
  'lh-meta': 1.4,
  'weight-normal': 400,
  'weight-strong': 600,
  'line-clamp-title': 2,
  'sp-1': 2,
  'sp-2': 4,
  'sp-3': 8,
  'sp-4': 12,
  'sp-5': 16,
  'sp-6': 24,
  'sp-7': 32,
  'sp-8': 48,
  'radius-xs': 2,
  'radius-sm': 4,
  'radius-md': 7,
  'radius-full': 999,
  'border-width': 1,
  'border-width-strong': 2,
  'focus-offset': 2,
  'overlay-margin': 8,
  'menu-offset': 4,
  'overlay-enter-scale': 0.98,
  'dur-state': 90,
  'dur-exit': 120,
  'dur-layer': 140,
  'dur-panel': 180,
  'dur-move': 200,
  'z-content': 0,
  'z-sticky': 10,
  'z-shell': 40,
  'z-drag': 50,
  'z-dropdown': 100,
  'z-layer': 200,
  'z-toast': 300,
  'z-tooltip': 400,
  'sidebar-width': 260,
  'sidebar-min': 200,
  'sidebar-max': 420,
  'sidebar-snap': 140,
  'sidebar-collapsed': 48,
  'panel-width': 420,
  'panel-min': 360,
  'panel-max': 640,
  'canvas-min': 480,
  'panel-enter-shift': 8,
  'resizer-hit': 8,
  'resizer-delay': 150,
  'resize-step': 16,
  'resize-step-big': 64,
  'canvas-header-height': 48,
  'statusbar-height': 24,
  'column-width': 288,
  'column-gap': 12,
  'icon-size': 16,
  'icon-stroke': 1.5,
  'icon-size-lg': 20,
  'avatar-xs': 16,
  'avatar-sm': 20,
  'avatar-md': 28,
  'avatar-stack-max': 3,
  'avatar-overlap': -6,
  'palette-width': 560,
  'palette-row': 36,
  'palette-input': 48,
  'palette-max': 360,
  'kbd-size': 18,
  'kbd-font-size': 11,
  'visually-hidden-size': 1,
  'spin-duration': 700,
  'spinner-size-xs': 12,
  'spinner-size-sm': 16,
  'spinner-size-md': 20,
  'spinner-size-lg': 24,
  'spinner-stroke-thin': 1.5,
  'spinner-stroke-thick': 2,
  'spinner-delay': 200,
  'spinner-min': 400,
  'progress-height': 2,
  'progress-run': 1200,
  'progress-breath': 0,
  'tooltip-max-width': 240,
  'tooltip-offset': 6,
  'tooltip-group-window': 300,
  'disabled-opacity': 0.45,
  'textarea-max-rows': 12,
  'pending-dot-size': 6,
  'checkbox-size': 16,
  'checkbox-glyph-size': 12,
  'switch-width': 28,
  'switch-height': 16,
  'switch-thumb': 10,
  'switch-thumb-stretch': 12,
  'switch-inset': 2,
  'menu-min-width': 200,
  'menu-max-width': 320,
  'menu-max-items': 10,
  'menu-radio-dot': 6,
  'popover-width': 300,
  'popover-width-wide': 360,
  'tag-height': 20,
  'tag-dot': 6,
  'tag-icon-size': 12,
  'tag-max-visible': 3,
  'undo-window': 8000,
  'tooltip-delay': 400,
  'highlight-remote': 400,
  'drag-threshold': 4,
  'row-height': 36,
  'control-height': 32,
  'control-height-sm': 24,
  'card-padding': 12,
  'card-gap': 8,
  'cell-padding-x': 8,
  'hit-min': 36,
  'button-pad-x': 12,
  'button-pad-x-sm': 8,
  'input-pad-x': 8,
  'segmented-height': 28,
} as const;
export type RawTokenName = keyof typeof raw;

/** Unit of the matching raw value. */
export const rawUnit = {
  'tint-dot-l': 'none',
  'tint-dot-c': 'none',
  'tint-fill-l': 'none',
  'tint-fill-c': 'none',
  'tint-fill-alpha': 'none',
  'tint-text-l': 'none',
  'tint-text-c': 'none',
  'type-display': 'px',
  'lh-display': 'none',
  'type-h1': 'px',
  'lh-h1': 'none',
  'type-h2': 'px',
  'lh-h2': 'none',
  'type-h3': 'px',
  'lh-h3': 'none',
  'type-body': 'px',
  'lh-body': 'none',
  'type-meta': 'px',
  'lh-meta': 'none',
  'weight-normal': 'none',
  'weight-strong': 'none',
  'line-clamp-title': 'none',
  'sp-1': 'px',
  'sp-2': 'px',
  'sp-3': 'px',
  'sp-4': 'px',
  'sp-5': 'px',
  'sp-6': 'px',
  'sp-7': 'px',
  'sp-8': 'px',
  'radius-xs': 'px',
  'radius-sm': 'px',
  'radius-md': 'px',
  'radius-full': 'px',
  'border-width': 'px',
  'border-width-strong': 'px',
  'focus-offset': 'px',
  'overlay-margin': 'px',
  'menu-offset': 'px',
  'overlay-enter-scale': 'none',
  'dur-state': 'ms',
  'dur-exit': 'ms',
  'dur-layer': 'ms',
  'dur-panel': 'ms',
  'dur-move': 'ms',
  'z-content': 'none',
  'z-sticky': 'none',
  'z-shell': 'none',
  'z-drag': 'none',
  'z-dropdown': 'none',
  'z-layer': 'none',
  'z-toast': 'none',
  'z-tooltip': 'none',
  'sidebar-width': 'px',
  'sidebar-min': 'px',
  'sidebar-max': 'px',
  'sidebar-snap': 'px',
  'sidebar-collapsed': 'px',
  'panel-width': 'px',
  'panel-min': 'px',
  'panel-max': 'px',
  'canvas-min': 'px',
  'panel-enter-shift': 'px',
  'resizer-hit': 'px',
  'resizer-delay': 'ms',
  'resize-step': 'px',
  'resize-step-big': 'px',
  'canvas-header-height': 'px',
  'statusbar-height': 'px',
  'column-width': 'px',
  'column-gap': 'px',
  'icon-size': 'px',
  'icon-stroke': 'px',
  'icon-size-lg': 'px',
  'avatar-xs': 'px',
  'avatar-sm': 'px',
  'avatar-md': 'px',
  'avatar-stack-max': 'none',
  'avatar-overlap': 'px',
  'palette-width': 'px',
  'palette-row': 'px',
  'palette-input': 'px',
  'palette-max': 'px',
  'kbd-size': 'px',
  'kbd-font-size': 'px',
  'visually-hidden-size': 'px',
  'spin-duration': 'ms',
  'spinner-size-xs': 'px',
  'spinner-size-sm': 'px',
  'spinner-size-md': 'px',
  'spinner-size-lg': 'px',
  'spinner-stroke-thin': 'px',
  'spinner-stroke-thick': 'px',
  'spinner-delay': 'ms',
  'spinner-min': 'ms',
  'progress-height': 'px',
  'progress-run': 'ms',
  'progress-breath': 'ms',
  'tooltip-max-width': 'px',
  'tooltip-offset': 'px',
  'tooltip-group-window': 'ms',
  'disabled-opacity': 'none',
  'textarea-max-rows': 'none',
  'pending-dot-size': 'px',
  'checkbox-size': 'px',
  'checkbox-glyph-size': 'px',
  'switch-width': 'px',
  'switch-height': 'px',
  'switch-thumb': 'px',
  'switch-thumb-stretch': 'px',
  'switch-inset': 'px',
  'menu-min-width': 'px',
  'menu-max-width': 'px',
  'menu-max-items': 'none',
  'menu-radio-dot': 'px',
  'popover-width': 'px',
  'popover-width-wide': 'px',
  'tag-height': 'px',
  'tag-dot': 'px',
  'tag-icon-size': 'px',
  'tag-max-visible': 'none',
  'undo-window': 'ms',
  'tooltip-delay': 'ms',
  'highlight-remote': 'ms',
  'drag-threshold': 'px',
  'row-height': 'px',
  'control-height': 'px',
  'control-height-sm': 'px',
  'card-padding': 'px',
  'card-gap': 'px',
  'cell-padding-x': 'px',
  'hit-min': 'px',
  'button-pad-x': 'px',
  'button-pad-x-sm': 'px',
  'input-pad-x': 'px',
  'segmented-height': 'px',
} as const satisfies Record<RawTokenName, 'px' | 'ms' | 'none'>;
