/* AUTO-GENERATED from tokens.css — do not edit by hand.
   Edit tokens.css and run: nx run ui-kit:generate-tokens */

export const PRIMITIVE_TOKENS = [
  'c-n-0',
  'c-n-50',
  'c-n-100',
  'c-n-150',
  'c-n-200',
  'c-n-300',
  'c-n-400',
  'c-n-500',
  'c-n-600',
  'c-n-700',
  'c-n-800',
  'c-n-900',
  'c-n-1000',
  'c-accent-100',
  'c-accent-200',
  'c-accent-300',
  'c-accent-400',
  'c-accent-500',
  'c-accent',
  'c-accent-600',
  'c-accent-700',
  'c-accent-800',
  'c-accent-900',
  'c-danger-100',
  'c-danger-300',
  'c-danger-500',
  'c-danger-700',
  'c-success-100',
  'c-success-300',
  'c-success-500',
  'c-success-700',
  'c-info-100',
  'c-info-300',
  'c-info-500',
  'c-info-700',
] as const;
export type PrimitiveToken = (typeof PRIMITIVE_TOKENS)[number];

export const TOKENS = [
  'bg-canvas',
  'bg-raised',
  'bg-sunken',
  'bg-hover',
  'bg-active',
  'bg-selected',
  'bg-accent-soft',
  'bg-danger-soft',
  'bg-scrim',
  'text-primary',
  'text-secondary',
  'text-muted',
  'text-disabled',
  'text-inverse',
  'text-accent',
  'text-on-accent',
  'text-danger',
  'border-hairline',
  'border-strong',
  'border-accent',
  'focus-ring',
  'state-overdue',
  'state-due-soon',
  'state-done',
  'state-info',
  'state-pending',
  'state-conflict',
  'shadow-raised',
  'shadow-overlay',
  'shadow-modal',
  'font-ui',
  'font-mono',
  'num-tabular',
  'type-display',
  'lh-display',
  'type-h1',
  'lh-h1',
  'type-h2',
  'lh-h2',
  'type-h3',
  'lh-h3',
  'type-body',
  'lh-body',
  'type-meta',
  'lh-meta',
  'weight-normal',
  'weight-strong',
  'line-clamp-title',
  'sp-1',
  'sp-2',
  'sp-3',
  'sp-4',
  'sp-5',
  'sp-6',
  'sp-7',
  'sp-8',
  'radius-xs',
  'radius-sm',
  'radius-md',
  'radius-full',
  'border-width',
  'border-width-strong',
  'focus-offset',
  'dur-state',
  'dur-exit',
  'dur-layer',
  'dur-panel',
  'dur-move',
  'ease-out',
  'ease-in',
  'ease-inout',
  'z-content',
  'z-sticky',
  'z-drag',
  'z-dropdown',
  'z-layer',
  'z-toast',
  'sidebar-width',
  'sidebar-width-min',
  'sidebar-width-max',
  'sidebar-collapsed',
  'panel-width',
  'panel-width-min',
  'panel-width-max',
  'canvas-header-height',
  'statusbar-height',
  'column-width',
  'column-gap',
  'icon-size',
  'icon-size-lg',
  'avatar-sm',
  'avatar-md',
  'palette-width',
  'palette-row',
  'undo-window',
  'spinner-delay',
  'tooltip-delay',
  'highlight-remote',
  'drag-threshold',
  'row-height',
  'control-height',
  'control-height-sm',
  'card-padding',
  'card-gap',
  'cell-padding-x',
  'hit-min',
] as const;
/** Token names of layers 2-3. Primitives (--c-*) are excluded on purpose: a component never sees them. */
export type TokenName = (typeof TOKENS)[number];

/** name → 'var(--name)'. For inline styles and CSS-in-JS. */
export const token = {
  'bg-canvas': 'var(--bg-canvas)',
  'bg-raised': 'var(--bg-raised)',
  'bg-sunken': 'var(--bg-sunken)',
  'bg-hover': 'var(--bg-hover)',
  'bg-active': 'var(--bg-active)',
  'bg-selected': 'var(--bg-selected)',
  'bg-accent-soft': 'var(--bg-accent-soft)',
  'bg-danger-soft': 'var(--bg-danger-soft)',
  'bg-scrim': 'var(--bg-scrim)',
  'text-primary': 'var(--text-primary)',
  'text-secondary': 'var(--text-secondary)',
  'text-muted': 'var(--text-muted)',
  'text-disabled': 'var(--text-disabled)',
  'text-inverse': 'var(--text-inverse)',
  'text-accent': 'var(--text-accent)',
  'text-on-accent': 'var(--text-on-accent)',
  'text-danger': 'var(--text-danger)',
  'border-hairline': 'var(--border-hairline)',
  'border-strong': 'var(--border-strong)',
  'border-accent': 'var(--border-accent)',
  'focus-ring': 'var(--focus-ring)',
  'state-overdue': 'var(--state-overdue)',
  'state-due-soon': 'var(--state-due-soon)',
  'state-done': 'var(--state-done)',
  'state-info': 'var(--state-info)',
  'state-pending': 'var(--state-pending)',
  'state-conflict': 'var(--state-conflict)',
  'shadow-raised': 'var(--shadow-raised)',
  'shadow-overlay': 'var(--shadow-overlay)',
  'shadow-modal': 'var(--shadow-modal)',
  'font-ui': 'var(--font-ui)',
  'font-mono': 'var(--font-mono)',
  'num-tabular': 'var(--num-tabular)',
  'type-display': 'var(--type-display)',
  'lh-display': 'var(--lh-display)',
  'type-h1': 'var(--type-h1)',
  'lh-h1': 'var(--lh-h1)',
  'type-h2': 'var(--type-h2)',
  'lh-h2': 'var(--lh-h2)',
  'type-h3': 'var(--type-h3)',
  'lh-h3': 'var(--lh-h3)',
  'type-body': 'var(--type-body)',
  'lh-body': 'var(--lh-body)',
  'type-meta': 'var(--type-meta)',
  'lh-meta': 'var(--lh-meta)',
  'weight-normal': 'var(--weight-normal)',
  'weight-strong': 'var(--weight-strong)',
  'line-clamp-title': 'var(--line-clamp-title)',
  'sp-1': 'var(--sp-1)',
  'sp-2': 'var(--sp-2)',
  'sp-3': 'var(--sp-3)',
  'sp-4': 'var(--sp-4)',
  'sp-5': 'var(--sp-5)',
  'sp-6': 'var(--sp-6)',
  'sp-7': 'var(--sp-7)',
  'sp-8': 'var(--sp-8)',
  'radius-xs': 'var(--radius-xs)',
  'radius-sm': 'var(--radius-sm)',
  'radius-md': 'var(--radius-md)',
  'radius-full': 'var(--radius-full)',
  'border-width': 'var(--border-width)',
  'border-width-strong': 'var(--border-width-strong)',
  'focus-offset': 'var(--focus-offset)',
  'dur-state': 'var(--dur-state)',
  'dur-exit': 'var(--dur-exit)',
  'dur-layer': 'var(--dur-layer)',
  'dur-panel': 'var(--dur-panel)',
  'dur-move': 'var(--dur-move)',
  'ease-out': 'var(--ease-out)',
  'ease-in': 'var(--ease-in)',
  'ease-inout': 'var(--ease-inout)',
  'z-content': 'var(--z-content)',
  'z-sticky': 'var(--z-sticky)',
  'z-drag': 'var(--z-drag)',
  'z-dropdown': 'var(--z-dropdown)',
  'z-layer': 'var(--z-layer)',
  'z-toast': 'var(--z-toast)',
  'sidebar-width': 'var(--sidebar-width)',
  'sidebar-width-min': 'var(--sidebar-width-min)',
  'sidebar-width-max': 'var(--sidebar-width-max)',
  'sidebar-collapsed': 'var(--sidebar-collapsed)',
  'panel-width': 'var(--panel-width)',
  'panel-width-min': 'var(--panel-width-min)',
  'panel-width-max': 'var(--panel-width-max)',
  'canvas-header-height': 'var(--canvas-header-height)',
  'statusbar-height': 'var(--statusbar-height)',
  'column-width': 'var(--column-width)',
  'column-gap': 'var(--column-gap)',
  'icon-size': 'var(--icon-size)',
  'icon-size-lg': 'var(--icon-size-lg)',
  'avatar-sm': 'var(--avatar-sm)',
  'avatar-md': 'var(--avatar-md)',
  'palette-width': 'var(--palette-width)',
  'palette-row': 'var(--palette-row)',
  'undo-window': 'var(--undo-window)',
  'spinner-delay': 'var(--spinner-delay)',
  'tooltip-delay': 'var(--tooltip-delay)',
  'highlight-remote': 'var(--highlight-remote)',
  'drag-threshold': 'var(--drag-threshold)',
  'row-height': 'var(--row-height)',
  'control-height': 'var(--control-height)',
  'control-height-sm': 'var(--control-height-sm)',
  'card-padding': 'var(--card-padding)',
  'card-gap': 'var(--card-gap)',
  'cell-padding-x': 'var(--cell-padding-x)',
  'hit-min': 'var(--hit-min)',
} as const satisfies Record<TokenName, string>;

/** Scalar values (px/ms/unitless) from the base :root — for JS logic. */
export const raw = {
  'type-display': 28,
  'lh-display': 1.2,
  'type-h1': 22,
  'lh-h1': 1.25,
  'type-h2': 18,
  'lh-h2': 1.3,
  'type-h3': 15,
  'lh-h3': 1.4,
  'type-body': 14,
  'lh-body': 1.5,
  'type-meta': 12,
  'lh-meta': 1.4,
  'weight-normal': 400,
  'weight-strong': 600,
  'line-clamp-title': 2,
  'sp-1': 2,
  'sp-2': 4,
  'sp-3': 8,
  'sp-4': 12,
  'sp-5': 16,
  'sp-6': 24,
  'sp-7': 32,
  'sp-8': 48,
  'radius-xs': 2,
  'radius-sm': 4,
  'radius-md': 7,
  'radius-full': 999,
  'border-width': 1,
  'border-width-strong': 2,
  'focus-offset': 2,
  'dur-state': 90,
  'dur-exit': 120,
  'dur-layer': 140,
  'dur-panel': 180,
  'dur-move': 200,
  'z-content': 0,
  'z-sticky': 10,
  'z-drag': 50,
  'z-dropdown': 100,
  'z-layer': 200,
  'z-toast': 300,
  'sidebar-width': 260,
  'sidebar-width-min': 200,
  'sidebar-width-max': 420,
  'sidebar-collapsed': 48,
  'panel-width': 420,
  'panel-width-min': 360,
  'panel-width-max': 640,
  'canvas-header-height': 48,
  'statusbar-height': 24,
  'column-width': 288,
  'column-gap': 12,
  'icon-size': 16,
  'icon-size-lg': 20,
  'avatar-sm': 20,
  'avatar-md': 28,
  'palette-width': 560,
  'palette-row': 36,
  'undo-window': 8000,
  'spinner-delay': 200,
  'tooltip-delay': 400,
  'highlight-remote': 400,
  'drag-threshold': 4,
  'row-height': 36,
  'control-height': 32,
  'control-height-sm': 24,
  'card-padding': 12,
  'card-gap': 8,
  'cell-padding-x': 8,
  'hit-min': 36,
} as const;
export type RawTokenName = keyof typeof raw;

/** Unit of the matching raw value. */
export const rawUnit = {
  'type-display': 'px',
  'lh-display': 'none',
  'type-h1': 'px',
  'lh-h1': 'none',
  'type-h2': 'px',
  'lh-h2': 'none',
  'type-h3': 'px',
  'lh-h3': 'none',
  'type-body': 'px',
  'lh-body': 'none',
  'type-meta': 'px',
  'lh-meta': 'none',
  'weight-normal': 'none',
  'weight-strong': 'none',
  'line-clamp-title': 'none',
  'sp-1': 'px',
  'sp-2': 'px',
  'sp-3': 'px',
  'sp-4': 'px',
  'sp-5': 'px',
  'sp-6': 'px',
  'sp-7': 'px',
  'sp-8': 'px',
  'radius-xs': 'px',
  'radius-sm': 'px',
  'radius-md': 'px',
  'radius-full': 'px',
  'border-width': 'px',
  'border-width-strong': 'px',
  'focus-offset': 'px',
  'dur-state': 'ms',
  'dur-exit': 'ms',
  'dur-layer': 'ms',
  'dur-panel': 'ms',
  'dur-move': 'ms',
  'z-content': 'none',
  'z-sticky': 'none',
  'z-drag': 'none',
  'z-dropdown': 'none',
  'z-layer': 'none',
  'z-toast': 'none',
  'sidebar-width': 'px',
  'sidebar-width-min': 'px',
  'sidebar-width-max': 'px',
  'sidebar-collapsed': 'px',
  'panel-width': 'px',
  'panel-width-min': 'px',
  'panel-width-max': 'px',
  'canvas-header-height': 'px',
  'statusbar-height': 'px',
  'column-width': 'px',
  'column-gap': 'px',
  'icon-size': 'px',
  'icon-size-lg': 'px',
  'avatar-sm': 'px',
  'avatar-md': 'px',
  'palette-width': 'px',
  'palette-row': 'px',
  'undo-window': 'ms',
  'spinner-delay': 'ms',
  'tooltip-delay': 'ms',
  'highlight-remote': 'ms',
  'drag-threshold': 'px',
  'row-height': 'px',
  'control-height': 'px',
  'control-height-sm': 'px',
  'card-padding': 'px',
  'card-gap': 'px',
  'cell-padding-x': 'px',
  'hit-min': 'px',
} as const satisfies Record<RawTokenName, 'px' | 'ms' | 'none'>;
