import { defineConfig } from 'vitest/config';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import { nxCopyAssetsPlugin } from '@nx/vite/plugins/nx-copy-assets.plugin';

export default defineConfig(() => ({
  root: import.meta.dirname,
  cacheDir: '../../../node_modules/.vite/packages/frontend/uploader',
  plugins: [nxViteTsPaths(), nxCopyAssetsPlugin(['*.md'])],
  test: {
    name: 'uploader',
    watch: false,
    globals: true,
    environment: 'node',
    include: ['{src,tests}/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
    reporters: ['default'],
    coverage: {
      reportsDirectory: '../../../coverage/packages/frontend/uploader',
      provider: 'v8' as const,
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.spec.ts',
        'src/**/index.ts',
        // Generated by wasm-bindgen; the Rust side has its own tests
        'src/hasher/wasm/**',
        'src/testing/**',
        // Only the worker global; everything it wires up is tested through UploadHost
        'src/worker/upload.worker.ts',
      ],
      reporter: ['text', 'html', 'lcov'],
      // Current level, rounded down. Raise when coverage grows; never lower silently.
      thresholds: {
        statements: 92,
        branches: 84,
        functions: 90,
        lines: 95,
      },
    },
  },
}));
