[package]
name = "main_service"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
default-run = "main_service"

[lib]
name = "main_app"
path = "src/lib.rs"

[[bin]]
name = "main_service"
path = "src/main.rs"

[[bin]]
name = "export-openapi-main"
path = "src/bin/export_openapi.rs"

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["macros"] }
chrono.workspace = true
error_handlers = { workspace = true, features = ["sqlx", "openapi"] }
lapin.workspace = true
mimalloc.workspace = true
serde.workspace = true
serde_json.workspace = true
sql_models.workspace = true
sqlx = { workspace = true, features = ["chrono", "uuid"] }
tokio = { workspace = true, features = ["sync"] }
tower-http = { workspace = true, features = ["cors"] }
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true
utoipa-swagger-ui = { workspace = true, features = ["axum", "vendored"] }
utils.workspace = true
uuid = { workspace = true, features = ["serde"] }

[dev-dependencies]
tower.workspace = true
